project_name: "user_srv"
md5_salt: "test"
logger:
  file_name: "logs/test.log"
  max_size: 1
  max_backups: 5
  max_age: 1
  compress: false

mysql:
  host: "127.0.0.1"
  port: 3306
  database: "test"
  username: "root"
  password: "123123"

consul:
  host: "127.0.0.1"
  port: 8500
  tags: ["test","user_srv"]