nacos:
  namespace_id: "user_srv"
  log_dir: "logs/nacos/log"
  cache_dir: "logs/nacos/cache"
  rotate_time: "1h"
  max_age: 3
  log_level: "error"
  username: "nacos"
  password: "nacos"
  ip_addr: "127.0.0.1"
  context_path: "/nacos"
  port: 8848
  scheme: "http"
  data_id: "user_srv.json"
  group: "dev"